gshs/urls.py
from django.urls import path
from gshs import views


app_name = 'gshs'
urlpatterns = [
    path('infogigi/gigi/<str:gigigubun>/', views.InfogigiLV.as_view(), name='infogigi_list'),
    path('infogigi/update/<int:pk>/', views.update_infogigi, name='update_infogigi'),
    path('infogigi/delete/<int:pk>/', views.delete_infogigi, name='delete_infogigi'),    
    path('infogigi/create/', views.create_infogigi, name='create_infogigi'), 
    path('infogigi/search/', views.SearchinfoLV.as_view(), name='search_infogigi'),
    path('infogigi/export-excel/', views.export_excel, name='export_excel'),
    #수리
    path('infogigi/suri/list/', views.RepairLV.as_view(), name='suri_list'),
    path('infogigi/suri/list/<int:pk>/', views.repairpk_list, name='suri_list_pk'),
    path('infogigi/suri/infogigi/', views.suri_infogigi, name='suri_infogigi'),    
    path('infogigi/suri/place/', views.suri_place, name='suri_place'),    
    path('infogigi/suri/search', views.SearchRepairLV.as_view(), name='search_suri'),    
    path('infogigi/suri/<int:pk>/', views.RepairPhotoUV.as_view(), name='suri_update'),
    path('infogigi/suri/delete/<int:pk>/', views.suri_delete, name='suri_delete'),
    # productbuy
    path('infogigi/productbuy/', views.ProductbuyLV.as_view(), name='productbuy_list'),
    path('infogigi/productbuy/search', views.SearchProductBuyLV.as_view(), name='search_productbuy'),
    path('infogigi/productbuy/create/', views.create_productbuy, name='create_productbuy'),
    path('infogigi/productbuy/update/<int:pk>/', views.update_productbuy, name='update_productbuy'),
    path('infogigi/productbuy/delete/<int:pk>/', views.delete_productbuy, name='delete_productbuy'),
    #재고
    path('infogigi/jaego/', views.JaegoLV.as_view(), name='jaego_list'),
    path('infogigi/jaego/search', views.SearchJaegoLV.as_view(), name='search_jaego'),
    path('infogigi/jaego/<int:pk>/', views.jaego_infogigi, name='jaego_infogigi'),  
    path('infogigi/jaego/rental/', views.jaego_rental, name='jaego_rental'),  
    path('infogigi/jaego/notuse/<int:pk>/', views.jaego_notuse, name='jaego_notuse'),  
    #기기렌탈 
    path('infogigi/gigirental/', views.GigirentalLV.as_view(), name='gigirental_list'), 
    path('infogigi/gigirental/receive/<int:pk>/', views.gigirental_receive, name='gigirental_receive'), 
    path('infogigi/gigirental/delete/<int:pk>/', views.gigirental_delete, name='gigirental_delete'), 
    #widget
    path('infogigi/widget/productgubun/', views.productgubun_select, name='productgubun_select'),     
    #People
    path('infogigi/people/', views.PeopleLV.as_view(), name='people_list'),
    path('infogigi/people/search/', views.SearchpeopleLV.as_view(), name='search_people'),
    path('infogigi/people/create/', views.PeopleCV.as_view(), name='create_people'),
    path('infogigi/people/update/<int:pk>/', views.PeopleUV.as_view(), name='update_people'),
    path('infogigi/people/delete/<int:pk>/', views.delete_people, name='people_delete'),
    # 소프트웨어 
    path('infogigi/softwarestock/create', views.create_softwarestock, name='create_softwarestock'),
    path('infogigi/softwarestock/', views.SoftwarestockLV.as_view(), name='softwarestock_list'),
    path('infogigi/softwarestock/rental/', views.software_rental, name='software_rental'),
    # 소프트웨어 렌탈
    path('infogigi/softwarerental/', views.SoftwarerentalLV.as_view(), name='softwarerental_list'),
    path('infogigi/softwarerental/receive/<int:pk>/', views.softwarerental_receive, name='softwarerental_receive'), 
    #부품 교환
    path('infogigi/bupum/list/', views.BupumLV.as_view(), name='bupum_list'),
    path('infogigi/bupum/change/', views.bupum_infogigi, name='bupum_infogigi'), 
    path('infogigi/bupum/search/', views.SearchbupumLV.as_view(), name='search_bupum'),
    path('infogigi/bupum/update/<int:pk>/', views.update_bupum, name='update_bupum'),
    path('infogigi/bupum/delete/<int:pk>/', views.delete_bupum, name='delete_bupum'),
    # 위치
    path('infogigi/place/list/<str:place_gubun>/', views.PlaceLV.as_view(), name='list_place'),
    path('infogigi/place/photo/<int:pk>/', views.photo_place, name='photo_place'),
    path('infogigi/place/photo/update/<int:pk>/', views.PlacePhotoUV.as_view(), name='photo_update_place'),
]  

mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('gshs/', include('gshs.urls')),  
    path('accounts/', include('accountapp.urls')),
    path('memo/', include('memo.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG: 
#     import debug_toolbar 
#     urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]


gshs/views.py
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from gshs.models import *
from django.views.generic import ListView, CreateView, UpdateView
from django.db.models import Q
from gshs.forms import InfogigiForm, RepairForm, ProductbuyForm, GigirentalForm, PeopleForm, SoftwarerentalForm, SoftwarestockForm, BupumchangeForm, PhotoForm
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.paginator import Paginator
from gshs.resources import InfogigiResource
from django.http import HttpResponse
import xlwt
from django.db.models import Value as V
from django.db.models.functions import Concat
from datetime import datetime, timezone 
from gshs.forms import PhotoInlineFormSet, PlaceImageFormSet
from django.urls import reverse_lazy
# from django.utils import timezone
from django.db import transaction 
import pytz
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib import messages


class InfogigiLV(ListView): 
    template_name = 'gshs/infogigi/gigihome.html'    
    paginate_by = 10   
 
    def get_queryset(self, **kwargs):
        self.gigigubun = self.kwargs['gigigubun']
        if self.gigigubun == 'all':
            queryset = Infogigi.objects.filter(status=True).select_related('productgubun','people','place')
        else:
             queryset = Infogigi.objects.filter(productgubun__sub_division=self.gigigubun, status=True).select_related('productgubun', 'people', 'place')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  
              
        gigi = Productgubun.objects.filter(main_division='infogigi').values('sub_division')      
        context["productgubun"] =gigi 
        context["gigigubun"] = self.gigigubun 
        paginator = context['paginator']
        page_numbers_range = 7  # Display only 7 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['gigi_count'] = paginator.count

        return context

class SearchinfoLV(ListView):    
    template_name = 'gshs/infogigi/gigihome.html'  
    paginate_by = 10    

    def get_queryset(self, **kwargs):
        # self.gigigubun = self.kwargs['gigigubun']
        self.word = self.request.GET.get('word')
        post_list = Infogigi.objects.filter(Q(status=True), Q(people__name__contains=self.word) | Q(ip__contains=self.word) | Q(place__room__contains=self.word))
        return post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        gigi = Productgubun.objects.filter(main_division='infogigi')
        context["productgubun"] =gigi
        context["gigigubun"] = 'all'
        paginator = context['paginator']
        page_numbers_range = 7  # Display only 7 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['gigi_count'] = paginator.count
        context['word'] = self.word
       
        return context

@login_required(login_url='/accounts/login/')
def save_infogigi_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()  
            if form.instance.productgubun.main_division == 'productbuy':
                Softwarestock.objects.create(model = form.instance.model, count = form.instance.count, remain = form.instance.count, price = form.instance.price)
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False    
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@login_required(login_url='/accounts/login/')
def create_infogigi(request):
    # creatview 사용시 initial={'gubun':'Notebook} 초기값 줄 수 있다.
    if request.method == 'POST':
        form = InfogigiForm(request.POST)
    else:
        form = InfogigiForm()
    return save_infogigi_form(request, form, 'gshs/infogigi/partial-infogigi-create.html')

@login_required
def create_productbuy(request):
    if request.method == 'POST':
        form = ProductbuyForm(request.POST)
    else:
        form = ProductbuyForm()
    return save_infogigi_form(request, form, 'gshs/productbuy/partial-productbuy-create.html')

@login_required
def update_infogigi(request, pk):
    infogigi = get_object_or_404(Infogigi, pk=pk)    
    if request.method == 'POST':
        form = InfogigiForm(request.POST, instance=infogigi)
    else:
        form = InfogigiForm(instance=infogigi)
    return save_infogigi_form(request, form, 'gshs/infogigi/partial-infogigi-update.html')

@login_required
def update_productbuy(request, pk):
    productbuy = get_object_or_404(Productbuy, pk=pk)    
    if request.method == 'POST':
        form = ProductbuyForm(request.POST, instance=productbuy)
    else:
        form = ProductbuyForm(instance=productbuy)
    return save_infogigi_form(request, form, 'gshs/productbuy/partial-productbuy-update.html')

@login_required
def delete_infogigi(request, pk):
    infogigi = get_object_or_404(Infogigi, pk=pk)
    infogigi.status = 0
    infogigi.save()   
    return redirect('gshs:infogigi_list', gigigubun='all')

@login_required
def delete_productbuy(request, pk):
    productbuy = get_object_or_404(Productbuy, pk=pk)
    productbuy.delete()
    return redirect('gshs:productbuy_list')

@login_required
def delete_people(request, pk):
    people = get_object_or_404(People, pk=pk)
    people.status = 0
    return redirect('gshs:people_list')

@login_required
def suri_infogigi(request):
    data = dict()
    if request.method == 'POST':
        form = RepairForm(request.POST)
        if form.is_valid():            
            form.save() 
            if request.FILES:
                try:
                    for img in request.FILES.getlist('images'):
                        # Photo 객체를 하나 생성한다.
                        photo = Photo()
                        # 외래키로 현재 생성한 Repair의 기본키를 참조한다.
                        photo.suri = form.instance
                        # imgs로부터 가져온 이미지 파일 하나를 저장한다.
                        photo.image = img
                        # 데이터베이스에 저장
                        photo.save()   
                # except Exception as ex: #에러 이름을 모를때
                #     print('에러가 발생 했습니다', ex) 
                except:
                    pass #이미지가 없어도 그냥 지나가도록
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False   
    else:
        suri_number = request.GET.get('number')
        # form = RepairForm()
        template_name = 'gshs/suri/partial-suri-create.html'  
        context = {'suri_number': suri_number} 
        data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@login_required
def suri_place(request):
    data = dict()
    if request.method == 'POST':
        form = RepairForm(request.POST)
        if form.is_valid():            
            form.save() 
            if request.FILES:
                try:
                    for img in request.FILES.getlist('images'):
                        # Photo 객체를 하나 생성한다.
                        photo = Photo()
                        # 외래키로 현재 생성한 Repair의 기본키를 참조한다.
                        photo.suri = form.instance
                        # imgs로부터 가져온 이미지 파일 하나를 저장한다.
                        photo.image = img
                        # 데이터베이스에 저장
                        photo.save()   
                # except Exception as ex: #에러 이름을 모를때
                #     print('에러가 발생 했습니다', ex) 
                except:
                    pass #이미지가 없어도 그냥 지나가도록
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False   
    else:
        place_number = request.GET.get('number')
        # form = RepairForm()
        template_name = 'gshs/suri/partial-suri-place-create.html'  
        context = {'place_number': place_number} 
        data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@login_required
def bupum_infogigi(request):
    data = dict()
    if request.method == 'POST':
        form = BupumchangeForm(request.POST)
        if form.is_valid(): 
            form.save(commit=False)
            infogigi_no = request.POST.get('bupum_number')
            info = Infogigi.objects.get(pk=infogigi_no)
            form.instance.infogigi = info
            form.save()            
            data['form_is_valid'] = True     
    else:
        data['form_is_valid'] = False
        bupum_number = request.GET.get('number')
        template_name = 'gshs/bupum/partial-bupum-create.html'  
        form = BupumchangeForm()
        # bupum_name = Productbuy.objects.filter(productgubun__sub_division='CONSUMABLE')

gshs/templates/gshs/infogigi/gigihome.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Infogigi{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'gshs/js/infogigis.js' %}"></script>
{% endblock %}

{% block content %}

<div style="float:left; width: 40%; display: inline-block;">
    <select class="form-select gigigubun" data-gigi="{{gigigubun}}">
        <option value='all'>ALL</option>
    {% for gubun in productgubun %}
        <option value={{gubun.sub_division}}>{{gubun.sub_division}}</option>
    {% endfor %}
    </select>
    <span style="border:1px solid #ccc; padding: 7px 10px; color: #f1f1f1; font-size: 14px; font-weight: bold; background-color:#616161;">{{ gigi_count }}</span>
</div>
<div style="display: inline-block; width: 60%;  text-align:right;">
    <form action="{% url 'gshs:search_infogigi' %}" method="get" style="display:inline-block;" >        
    <input style="height:32px;padding:0 10px;" type="text" name="word" class="form-class" value={{ word }}> 
    <button class="custom-btn" style="margin-top:2px;">
        <i class="fas fa-search"></i>
    </button> 
    </form> 
    <span style="margin-left:10px;">
        <button class="custom-btn js-create-infogigi" data-url="{% url 'gshs:create_infogigi' %}" title="새글 쓰기">
        <i class="far fa-plus-square"></i>
        </button>
    </span> 
</div>

<table class="custom-table" id="infogigi-table">
    <thead style="font-size: 14px;">
        <tr>
            <th>구분</th>
            <th>구매일</th> 
            {% if gigigubun == "NOTEBOOK" or gigigubun == "DESKTOP" or gigigubun == "all" %}
                <th>성명</th>
            {% endif %}            
            <th>위치</th>
            <th>제조사</th>
            <th>모델명</th>
            {% if gigigubun == "PRINTER" or gigigubun == "all" %}
                <th>컬러</th>
            {% endif %}                
            <th>Ip</th>
            <th>비고</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% include './partial-infogigi-list.html' %}
    </tbody>
</table>

<button class="custom-btn js-create-infogigi" data-url="{% url 'gshs:create_infogigi' %}" title="새글 쓰기">
    <i class="far fa-plus-square"></i>
</button>  

<div style="margin-top:20px;">
    {% include 'gshs/snippet/_pagination.html' with page_obj=page_obj page_range=page_range %}
</div>
<div class="modal fade" id="modal-infogigi">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

{% endblock content %}

gshs/templates/gshs/infogigi/partial-infogigi-create.html
<form method="post" action="{% url 'gshs:create_infogigi' %}" class="js-infogigi-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Create Infogigi</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% include 'gshs/snippet/partial-infogigi-form.html'%}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-outline-info">Create</button>
    </div>
</form>

gshs/templates/gshs/infogigi/partial-infogigi-delete.html
<form method="post" action="{% url 'gshs:delete_infogigi' pk %}" class="js-infogigi-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">기기 삭제 확인</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead"><strong>{{ infogigi.model }}</strong>을 삭제 할까요?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </div>
</form>

gshs/templates/gshs/infogigi/partial-infogigi-list.html
{% for item in object_list %}
    <tr>
        <td>{{ item.productgubun.sub_division }}</td>
        <td>{{ item.buy_date|date:'Y.m.d'}}</td>
        {% if gigigubun == "NOTEBOOK" or gigigubun == "DESKTOP" or gigigubun == "all" %}
            <td>{{ item.people }}</td>
        {% endif %}    
        <td>{{ item.place }}</td>
        <td>{{ item.maker }}</td>
        <td>{{ item.model }}</td>
        {% if gigigubun == "PRINTER" or gigigubun == "all" %}
            <td>{{ item.color }}</td>
        {% endif %}
        <td>{{ item.ip }}</td>
        <td>{{ item.bigo }}</td>
        <td>               
            <button class="custom-btn js-update-infogigi" data-url="{% url 'gshs:update_infogigi' item.id %}" title="글 수정">
                <i class="fas fa-edit"></i>
            </button> 
            <button class="custom-btn js-suri-infogigi {{ item.id }}" data-url="{% url 'gshs:suri_infogigi'%}" title="기기 수리">
                <i class="fas fa-tools"></i>
            </button>    
            <button class="custom-btn js-bupum-infogigi {{ item.id }}" data-url="{% url 'gshs:bupum_infogigi'%}" title="소모품 교환">
                <i class="fas fa-exchange-alt"></i>
            </button> 
            <button class="custom-btn js-jaego-infogigi" id="gigimove" data-url="{% url 'gshs:jaego_infogigi' item.id %}" title="재고 테이블로 이동">
                <i class="fas fa-archive"></i>
            </button>  
                      
            <a class="del-btn" type="button" href="{% url 'gshs:delete_infogigi' item.id %}" onclick="return confirm('정말 삭제하시겠습니까?')" title="글 삭제">
                <i class="fas fa-trash"></i>
            </a>
        </td>
    </tr>
{% empty %}
<div class="card" style="margin-top:50px;">
    <div class="card-header">
        Search Result
    </div>
    <div class="card-body" style="text-align:center;">
        <h2>검색 결과가 없습니다.</h2>            
    </div>
</div> 
{% endfor %}



gshs/templates/gshs/infogigi/partial-infogigi-update.html
<form method="post" action="{% url 'gshs:update_infogigi' form.instance.pk %}" class="js-infogigi-update-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Update Infogigi</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% include 'gshs/snippet/partial-infogigi-form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-outline-info">Update</button>
    </div>
</form>