gshs/urls.py
from django.urls import path
from gshs import views


app_name = 'gshs'
urlpatterns = [
    path('infogigi/gigi/<str:gigigubun>/', views.InfogigiLV.as_view(), name='infogigi_list'),
    path('infogigi/update/<int:pk>/', views.update_infogigi, name='update_infogigi'),
    path('infogigi/delete/<int:pk>/', views.delete_infogigi, name='delete_infogigi'),    
    path('infogigi/create/', views.create_infogigi, name='create_infogigi'), 
    path('infogigi/search/', views.SearchinfoLV.as_view(), name='search_infogigi'),
    path('infogigi/export-excel/', views.export_excel, name='export_excel'),
    #수리
    path('infogigi/suri/list/', views.RepairLV.as_view(), name='suri_list'),
    path('infogigi/suri/list/<int:pk>/', views.repairpk_list, name='suri_list_pk'),
    path('infogigi/suri/infogigi/', views.suri_infogigi, name='suri_infogigi'),    
    path('infogigi/suri/place/', views.suri_place, name='suri_place'),    
    path('infogigi/suri/search', views.SearchRepairLV.as_view(), name='search_suri'),    
    path('infogigi/suri/<int:pk>/', views.RepairPhotoUV.as_view(), name='suri_update'),
    path('infogigi/suri/delete/<int:pk>/', views.suri_delete, name='suri_delete'),
    # productbuy
    path('infogigi/productbuy/', views.ProductbuyLV.as_view(), name='productbuy_list'),
    path('infogigi/productbuy/search', views.SearchProductBuyLV.as_view(), name='search_productbuy'),
    path('infogigi/productbuy/create/', views.create_productbuy, name='create_productbuy'),
    path('infogigi/productbuy/update/<int:pk>/', views.update_productbuy, name='update_productbuy'),
    path('infogigi/productbuy/delete/<int:pk>/', views.delete_productbuy, name='delete_productbuy'),
    #재고
    path('infogigi/jaego/', views.JaegoLV.as_view(), name='jaego_list'),
    path('infogigi/jaego/search', views.SearchJaegoLV.as_view(), name='search_jaego'),
    path('infogigi/jaego/<int:pk>/', views.jaego_infogigi, name='jaego_infogigi'),  
    path('infogigi/jaego/rental/', views.jaego_rental, name='jaego_rental'),  
    path('infogigi/jaego/notuse/<int:pk>/', views.jaego_notuse, name='jaego_notuse'),  
    #기기렌탈 
    path('infogigi/gigirental/', views.GigirentalLV.as_view(), name='gigirental_list'), 
    path('infogigi/gigirental/receive/<int:pk>/', views.gigirental_receive, name='gigirental_receive'), 
    path('infogigi/gigirental/delete/<int:pk>/', views.gigirental_delete, name='gigirental_delete'), 
    #widget
    path('infogigi/widget/productgubun/', views.productgubun_select, name='productgubun_select'),     
    #People
    path('infogigi/people/', views.PeopleLV.as_view(), name='people_list'),
    path('infogigi/people/search/', views.SearchpeopleLV.as_view(), name='search_people'),
    path('infogigi/people/create/', views.PeopleCV.as_view(), name='create_people'),
    path('infogigi/people/update/<int:pk>/', views.PeopleUV.as_view(), name='update_people'),
    path('infogigi/people/delete/<int:pk>/', views.delete_people, name='people_delete'),
    # 소프트웨어 
    path('infogigi/softwarestock/create', views.create_softwarestock, name='create_softwarestock'),
    path('infogigi/softwarestock/', views.SoftwarestockLV.as_view(), name='softwarestock_list'),
    path('infogigi/softwarestock/rental/', views.software_rental, name='software_rental'),
    # 소프트웨어 렌탈
    path('infogigi/softwarerental/', views.SoftwarerentalLV.as_view(), name='softwarerental_list'),
    path('infogigi/softwarerental/receive/<int:pk>/', views.softwarerental_receive, name='softwarerental_receive'), 
    #부품 교환
    path('infogigi/bupum/list/', views.BupumLV.as_view(), name='bupum_list'),
    path('infogigi/bupum/change/', views.bupum_infogigi, name='bupum_infogigi'), 
    path('infogigi/bupum/search/', views.SearchbupumLV.as_view(), name='search_bupum'),
    path('infogigi/bupum/update/<int:pk>/', views.update_bupum, name='update_bupum'),
    path('infogigi/bupum/delete/<int:pk>/', views.delete_bupum, name='delete_bupum'),
    # 위치
    path('infogigi/place/list/<str:place_gubun>/', views.PlaceLV.as_view(), name='list_place'),
    path('infogigi/place/photo/<int:pk>/', views.photo_place, name='photo_place'),
    path('infogigi/place/photo/update/<int:pk>/', views.PlacePhotoUV.as_view(), name='photo_update_place'),
]  

mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('gshs/', include('gshs.urls')),  
    path('accounts/', include('accountapp.urls')),
    path('memo/', include('memo.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG: 
#     import debug_toolbar 
#     urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]


gshs/models.py
from django.db import models
from datetime import datetime 
from django.core.exceptions import ValidationError
from django.db.models.fields import BLANK_CHOICE_DASH
from django.urls import reverse


class Infogigi(models.Model):
    productgubun = models.ForeignKey("gshs.Productgubun", on_delete=models.CASCADE, null=True, blank=True)
    buy_date = models.DateField(blank=True, null=True)
    people = models.ForeignKey("gshs.People", on_delete=models.CASCADE, null=True, blank=True, limit_choices_to = {'status': True})
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)    
    maker = models.CharField(max_length=50)
    model = models.CharField(max_length=100)  
    color_choices = (
        ('흑백', '흑백'),
        ('컬러', '컬러'),
    )  
    color = models.CharField(max_length=6, choices=color_choices, null=True, blank=True)    
    ip = models.CharField(max_length=20, blank=True, null=True)  
    status = models.BooleanField(default=True)  
    bigo = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ['productgubun','buy_date']
        db_table = 'infogigi'

    def __str__(self):
        return '{}'.format( self.model)

class Place(models.Model):
    building = models.CharField(max_length=50, null=True, blank=True)
    room = models.CharField(max_length=50, default=0, null=False, blank=True)
    buseo_choices = (
        ('부서', '부서'),
        ('강의실', '강의실'),
        ('강당', '강당'),
        ('실험실', '실험실'),
        ('기타', '기타'),
    )
    buseo = models.CharField(max_length=30, choices=buseo_choices)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['building']
        db_table = 'place'

    def __str__(self):
        return '({}) {}'.format(self.building, self.room)

class People(models.Model):
    name = models.CharField(u'성명', max_length=50, null=True, blank=True)  
    address = models.CharField('주소',max_length=100, null=True, blank=True)  
    phone_number = models.CharField(u'핸드폰', max_length=20, blank=True, null=True)
    tel_number = models.CharField(u'내선', max_length=5, blank=True, null=True)
    status = models.BooleanField('재직', default=True)
    bigo = models.CharField('비고', max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['name']
        db_table = 'people'

    def __str__(self):
        return '{}'.format(self.name)

class Jaego(models.Model):
    created_date = models.DateField(auto_now_add=True)    
    infogigi = models.ForeignKey("gshs.Infogigi", on_delete=models.SET_NULL, null=True)
    rental_choices = (
        ('yes', '대여가능'),
        ('no', '대여중'),
    )
    rental_status = models.CharField(max_length=3, choices=rental_choices, default='yes', null=False, blank=True)
    not_use = models.BooleanField(default=False)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-rental_status', '-created_date']
        db_table = 'jaego'

    def __str__(self):
        return '{}'.format(self.infogigi)

class Gigirental(models.Model):
    rental_date = models.DateField(auto_now_add=True)
    due_date = models.DateField(null=True, blank=True)
    jaego = models.ForeignKey("gshs.Jaego", on_delete=models.CASCADE, blank=True)
    people = models.ForeignKey("gshs.People", on_delete=models.CASCADE, null=True, blank=True, limit_choices_to = {'status': True})
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-rental_date']
        db_table = 'gigirental'

    def __str__(self):
        return '{}'.format(self.rental_date)

    def get_absolute_url(self):
        return reverse('gshs:gigirental_list')

class Repair(models.Model):
    created_date = models.DateField(auto_now_add=True)
    infogigi = models.ForeignKey("gshs.Infogigi", on_delete=models.SET_NULL, null=True, blank=True)
    place = models.ForeignKey("gshs.Place", on_delete=models.SET_NULL, null=True, blank=True)
    cause = models.CharField(max_length=200)
    result = models.TextField()      
    price = models.PositiveIntegerField(default=0, null=False, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-created_date']
        db_table = 'repair'

    def __str__(self):
        return '[{}] {}'.format(self.cause, self.result)

    def get_absolute_url(self):
        return reverse('gshs:suri_list')
    

class Productbuy(models.Model):
    created_date = models.DateField(auto_now_add=True)
    productgubun = models.ForeignKey("gshs.Productgubun", on_delete=models.CASCADE, null=True, blank=True)
    vendor = models.ForeignKey("gshs.Vendor", on_delete=models.CASCADE, null=True, blank=True)
    maker = models.CharField(max_length=50, null=True, blank=True)
    model = models.CharField(max_length=100)
    count = models.PositiveSmallIntegerField(default=1, blank=True)
    price = models.PositiveIntegerField(default=0, null=False, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['productgubun', 'model']
        db_table = 'productbuy'

    def __str__(self):
        return '{}'.format(self.model)

class Vendor(models.Model):
    created_date = models.DateField(auto_now_add=True)
    company = models.CharField(max_length=100)
    address = models.CharField(max_length=100, null=True, blank=True)
    damdang_name = models.CharField(max_length=20, null=True, blank=True)
    tel = models.CharField(max_length=20, null=True, blank=True)
    bigo = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ['company']
        db_table = 'vendor'

    def __str__(self):
        return f'{self.company}'


class Bupumchange(models.Model):
    created_date = models.DateField(auto_now_add=True)
    infogigi = models.ForeignKey("gshs.Infogigi", on_delete=models.SET_NULL, null=True, blank=True)
    productbuy = models.ForeignKey("gshs.Productbuy", on_delete=models.SET_NULL, null=True)
    count = models.PositiveSmallIntegerField(default=1, null=False, blank=True)
    price = models.PositiveIntegerField(default=0, null=False, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-created_date']
        db_table = 'bupumchange'

    # def __str__(self):
    #     return '{}'.format(self.productbuy)
class Productgubun(models.Model):
    main_division = models.CharField(max_length=30, default='infogigi')
    sub_division = models.CharField(max_length=50)

    class Meta:
        db_table = 'productgubun'

    def __str__(self):
        return '{} / {}'.format(self.main_division,self.sub_division)

def file_size(value): 
    limit = 3 * 1024 * 1024 
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MB.')

class Photo(models.Model):
    suri = models.ForeignKey("gshs.Repair", on_delete=models.CASCADE, null=True, blank=True)
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(validators=[file_size], upload_to = "images/%Y/%m", null=False, blank=True) 

    class Meta:
        db_table = 'photo'

    # def delete(self, *args, **kargs):
    #     if not self.image:
    #         self.__class__.objects.delete()
    #     super().delete(*args, **kargs)

class Softwarestock(models.Model):
    created_date = models.DateField(auto_now_add=True)
    maker = models.CharField(max_length=50, null=True, blank=True)
    model = models.CharField(max_length=100)
    license = models.TextField(null=True)
    count = models.PositiveSmallIntegerField(default=1, blank=True)
    price = models.PositiveIntegerField(default=0, null=False, blank=True) 
    remain = models.PositiveSmallIntegerField(null=True, blank=True) 

    class Meta:
        db_table = 'softwarestock'

    def __str__(self):
        return '{}'.format(self.model)

    # @property
    # def remaining2(self):
    #     if self.remaining is not None:
    #         return self.remaining
    #     return self.productbuy.count
    
class Softwarerental(models.Model):
    rental_date = models.DateField(auto_now_add=True)
    due_date = models.DateField(null=True, blank=True)
    softwarestock = models.ForeignKey("gshs.Softwarestock", on_delete=models.CASCADE, null=False, blank=True)    
    people = models.ForeignKey("gshs.People", on_delete=models.CASCADE, null=True, blank=True, limit_choices_to = {'status': True})
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)
    count = models.PositiveSmallIntegerField(default=1, blank=True, help_text='남은 수량 보다 많이 입력하지마세요.!')
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-rental_date']
        db_table = 'softwarerental'

gshs/forms.py
from django import forms
from django.forms import inlineformset_factory
from gshs.models import Infogigi, Productbuy, Repair, Jaego, Photo, Gigirental, People, Softwarerental, Softwarestock, Bupumchange, Productgubun, Place
from gshs.widgets import AutoCompleteWidget, DatePickerWidget
from django.urls import reverse_lazy
from gshs.common.image_custom_widget import PreviewImageFileWidget

PhotoInlineFormSet = inlineformset_factory(Repair, Photo,\
    fields=['image',], extra=3)

class InfogigiForm(forms.ModelForm):  
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['productgubun'].queryset = Productgubun.objects.filter(main_division='infogigi')       


    class Meta:
        model = Infogigi
        fields = '__all__'  
        # widgets = {
        #     'productgubun': AutoCompleteWidget(ajax_url=reverse_lazy('gshs:productgubun_select')),
        #     'buy_date' : DatePickerWidget,
        # }         

class RepairForm(forms.ModelForm):
    class Meta:
        model = Repair
        fields = '__all__'

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['image'].required = False #file 값이 없더라도 view에서 유효성 검사에서 오류를 발생시키지 않도록 해준다
    #     self.fields['image'].widget.attrs.update({'class':'form-control-file'})
    #     self.fields['image'].multiple = True

class ProductbuyForm(forms.ModelForm):  
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['productgubun'].queryset = Productgubun.objects.all()    

    class Meta:
        model = Productbuy
        fields = '__all__'

class JaegoForm(forms.ModelForm):    
    class Meta:
        model = Jaego
        fields = '__all__'

class BupumchangeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['productbuy'].queryset = Productbuy.objects.filter(productgubun__main_division='consumables').select_related('productgubun')  

    class Meta:
        model = Bupumchange
        fields = ['productbuy','count','price','bigo']

class GigirentalForm(forms.ModelForm):    
    class Meta:
        model = Gigirental
        fields = ['jaego','people', 'place', 'bigo']
        widgets = {
            'jaego': forms.HiddenInput
        }

class PeopleForm(forms.ModelForm):    
    class Meta:
        model = People
        fields = '__all__'
    # def save(self, **kwargs):
    #     gigirental = super().save(commit=False)         # 부모메서드 호출 
    #     gigirental.infogigi.id = kwargs.get('infogigi_no', None)
    #     post.save()
class SoftwarestockForm(forms.ModelForm):
    class Meta:
        model = Softwarestock 
        fields = '__all__'
        widgets = {
            'remain': forms.HiddenInput
        }
        
class SoftwarerentalForm(forms.ModelForm):
    class Meta:
        model = Softwarerental
        fields = ['softwarestock','people', 'place', 'count', 'bigo']
        widgets = {
            'softwarestock': forms.HiddenInput
        }

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['place', 'image']
        # widgets = {
        #     'image': PreviewImageFileWidget()
        # }
PlaceImageFormSet = inlineformset_factory(Place, Photo,\
    fields=['image',], extra=2)

gshs/templates/gshs/snippet/_pagination.html
{% if is_paginated %}
<ul class="pagination justify-content-center"">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?word={{ word }}&page={{ page_obj.previous_page_number }}">PREV</a></li>
    {% else %}
        <li class="disabled page-item"><a class="page-link" href="#"><span>PREV</span></a></li>
    {% endif %}
    {% for i in page_range %}
        {% if page_obj.number == i %}
        <li class="active page-item"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?word={{ word }}&page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?word={{ word }}&page={{ page_obj.next_page_number }}">NEXT</a></li>
    {% else %}
        <li class="disabled page-item"><a class="page-link" href="#"><span>NEXT</span></a></li>
    {% endif %}
</ul>
{% endif %}

gshs/templates/gshs/snippet/partial-bupum-form.html
{% load widget_tweaks %}
{% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">        
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for text in field %}
            <small style="color: red;">{{ field.help_text|safe }}</small>
        {% endfor %}
        {% for error in field.errors %}
            <p class="help-block" sytle="color:red">{{ error }}</p>
        {% endfor %}        
    </div>   
{% endfor %}
<input name="bupum_number" type="hidden" value={{ bupum_number }}>

gshs/templates/gshs/snippet/partial-form.html
{% load widget_tweaks %}
{% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">        
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for text in field %}
            <small style="color: red;">{{ field.help_text|safe }}</small>
        {% endfor %}
        {% for error in field.errors %}
            <p class="help-block" sytle="color:red">{{ error }}</p>
        {% endfor %}        
    </div>   
{% endfor %}
<input name="transfer_no" type="hidden" value="{{ transfer_no }}">

gshs/templates/gshs/snippet/partial-infogigi-form-1.html
{% if form.errors %}
    <div class="alert alert-danger" role="alert">
    {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
    {% endfor %}
    </div>
{% endif %}
<!-- 오류표시 End -->
<div class="form-group">
    <label for="productgubun">제품구분</label>
    <input type="text" class="form-control" name="productgubun" id="productgubun" value="{{ form.productgubun.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="buy_date">구매일</label>
    <input type="date" class="form-control" name="buy_date" id="buy_date" value="{{ form.buy_date.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="people">성명</label>
    <input type="text" class="form-control" name="people" id="people" value="{{ form.people.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="place">장소</label>
    <input type="text" class="form-control" name="place" id="place" value="{{ form.place.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="maker">제조사</label>
    <input type="text" class="form-control" name="maker" id="maker" value="{{ form.maker.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="model">모델명</label>
    <input type="text" class="form-control" name="model" id="model" value="{{ form.model.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="color">색상</label>
    <input type="text" class="form-control" name="color" id="color" value="{{ form.color.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="ip">IP</label>
    <input type="text" class="form-control" name="ip" id="ip" value="{{ form.ip.value|default_if_none:'' }}">
</div>
<div class="form-group">
    <label for="status">상태</label>
    <input type="checkbox" class="form-control" name="status" id="status" checked>
</div>
<div class="form-group">
    <label for="bigo">비고</label>
    <input type="text" class="form-control" name="bigo" id="bigo" value="{{ form.bigo.value|default_if_none:'' }}">
</div>

gshs/templates/gshs/snippet/partial-infogigi-form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>                
        {% if field == form.buy_date %}  
            {% render_field field type="date" class="form-control" %}      
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}
        {% for error in field.errors %}
            <p class="help-block" sytle="color:red">{{ error }}</p>
        {% endfor %}       
    </div>
{% endfor %}

gshs/templates/gshs/snippet/partial-rental-form.html
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_jaego">Stock</label>
    <input type="text" name="jaego" id="id_jaego" class="form-control" value={{ jaego_no }}>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_people">People</label>
    <select name="people" id="id_people" class="form-control">
        <option value selected>--------</option>
        {% for item in People.objects.values('id','name') %}
            <option value="{{ item['id'] }}">{{ item['name'] }}</option>
        {% endfor %}
    </select>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_place">Place</label>
    <select name="place" id="id_place" class="form-control">
        <option value selected>--------</option>
        {% for item in Place.objects.values('id','building', 'room') %}
            <option value="{{ item['id'] }}">{{ item['building'] / item['building'] }}</option>
        {% endfor %}
    </select>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_bigo">Bigo</label>
    <input type="text" name="bigo" id="id_bigo" class="form-control" maxlength="100">
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>

gshs/templates/gshs/snippet/partial-suri-form.html
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_infogigi">Gubun</label>
    <input type="text" name="infogigi" id="id_infogigi" class="form-control" value={{ suri_number }}>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_cause">Cause</label>
    <input type="text" name="cause" id="id_cause" class="form-control" required>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_result">Result</label>
    <textarea name="result" cols="40" rows="10" id="id_result" class="form-control" required></textarea>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_price">Price</label>
    <input type="number" name="price" id="id_price" class="form-control" value="0" min="0">
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_bigo">Bigo</label>
    <input type="text" name="bigo" id="id_bigo" class="form-control" maxlength="100">
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_images">Images</label>
    <input type="file" name="images" id="id_images" class="form-control-file" multiple  onchange="checkSize(this)">
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>

gshs/templates/gshs/snippet/partial-suri-place-form.html
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_place">Gubun</label>
    <input type="text" name="place" id="id_place" class="form-control" value={{ place_number }}>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_cause">Cause</label>
    <input type="text" name="cause" id="id_cause" class="form-control" required>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_result">Result</label>
    <textarea name="result" cols="40" rows="10" id="id_result" class="form-control" required></textarea>
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_price">Price</label>
    <input type="number" name="price" id="id_price" class="form-control" value="0" min="0">
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_bigo">Bigo</label>
    <input type="text" name="bigo" id="id_bigo" class="form-control" maxlength="100">
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="id_images">Images</label>
    <input type="file" name="images" id="id_images" class="form-control-file" multiple  onchange="checkSize(this)">
    {% for error in field.errors %}
        <p class="help-block" sytle="color:red">{{ error }}</p>
    {% endfor %}
</div>