gshs/urls.py
from django.urls import path
from gshs import views


app_name = 'gshs'
urlpatterns = [
    path('infogigi/gigi/<str:gigigubun>/', views.InfogigiLV.as_view(), name='infogigi_list'),
    path('infogigi/update/<int:pk>/', views.update_infogigi, name='update_infogigi'),
    path('infogigi/delete/<int:pk>/', views.delete_infogigi, name='delete_infogigi'),    
    path('infogigi/create/', views.create_infogigi, name='create_infogigi'), 
    path('infogigi/search/', views.SearchinfoLV.as_view(), name='search_infogigi'),
    path('infogigi/export-excel/', views.export_excel, name='export_excel'),
    #수리
    path('infogigi/suri/list/', views.RepairLV.as_view(), name='suri_list'),
    path('infogigi/suri/list/<int:pk>/', views.repairpk_list, name='suri_list_pk'),
    path('infogigi/suri/infogigi/', views.suri_infogigi, name='suri_infogigi'),    
    path('infogigi/suri/place/', views.suri_place, name='suri_place'),    
    path('infogigi/suri/search', views.SearchRepairLV.as_view(), name='search_suri'),    
    path('infogigi/suri/<int:pk>/', views.RepairPhotoUV.as_view(), name='suri_update'),
    path('infogigi/suri/delete/<int:pk>/', views.suri_delete, name='suri_delete'),
    # productbuy
    path('infogigi/productbuy/', views.ProductbuyLV.as_view(), name='productbuy_list'),
    path('infogigi/productbuy/search', views.SearchProductBuyLV.as_view(), name='search_productbuy'),
    path('infogigi/productbuy/create/', views.create_productbuy, name='create_productbuy'),
    path('infogigi/productbuy/update/<int:pk>/', views.update_productbuy, name='update_productbuy'),
    path('infogigi/productbuy/delete/<int:pk>/', views.delete_productbuy, name='delete_productbuy'),
    #재고
    path('infogigi/jaego/', views.JaegoLV.as_view(), name='jaego_list'),
    path('infogigi/jaego/search', views.SearchJaegoLV.as_view(), name='search_jaego'),
    path('infogigi/jaego/<int:pk>/', views.jaego_infogigi, name='jaego_infogigi'),  
    path('infogigi/jaego/rental/', views.jaego_rental, name='jaego_rental'),  
    path('infogigi/jaego/notuse/<int:pk>/', views.jaego_notuse, name='jaego_notuse'),  
    #기기렌탈 
    path('infogigi/gigirental/', views.GigirentalLV.as_view(), name='gigirental_list'), 
    path('infogigi/gigirental/receive/<int:pk>/', views.gigirental_receive, name='gigirental_receive'), 
    path('infogigi/gigirental/delete/<int:pk>/', views.gigirental_delete, name='gigirental_delete'), 
    #widget
    path('infogigi/widget/productgubun/', views.productgubun_select, name='productgubun_select'),     
    #People
    path('infogigi/people/', views.PeopleLV.as_view(), name='people_list'),
    path('infogigi/people/search/', views.SearchpeopleLV.as_view(), name='search_people'),
    path('infogigi/people/create/', views.PeopleCV.as_view(), name='create_people'),
    path('infogigi/people/update/<int:pk>/', views.PeopleUV.as_view(), name='update_people'),
    path('infogigi/people/delete/<int:pk>/', views.delete_people, name='people_delete'),
    # 소프트웨어 
    path('infogigi/softwarestock/create', views.create_softwarestock, name='create_softwarestock'),
    path('infogigi/softwarestock/', views.SoftwarestockLV.as_view(), name='softwarestock_list'),
    path('infogigi/softwarestock/rental/', views.software_rental, name='software_rental'),
    # 소프트웨어 렌탈
    path('infogigi/softwarerental/', views.SoftwarerentalLV.as_view(), name='softwarerental_list'),
    path('infogigi/softwarerental/receive/<int:pk>/', views.softwarerental_receive, name='softwarerental_receive'), 
    #부품 교환
    path('infogigi/bupum/list/', views.BupumLV.as_view(), name='bupum_list'),
    path('infogigi/bupum/change/', views.bupum_infogigi, name='bupum_infogigi'), 
    path('infogigi/bupum/search/', views.SearchbupumLV.as_view(), name='search_bupum'),
    path('infogigi/bupum/update/<int:pk>/', views.update_bupum, name='update_bupum'),
    path('infogigi/bupum/delete/<int:pk>/', views.delete_bupum, name='delete_bupum'),
    # 위치
    path('infogigi/place/list/<str:place_gubun>/', views.PlaceLV.as_view(), name='list_place'),
    path('infogigi/place/photo/<int:pk>/', views.photo_place, name='photo_place'),
    path('infogigi/place/photo/update/<int:pk>/', views.PlacePhotoUV.as_view(), name='photo_update_place'),
]  

mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('gshs/', include('gshs.urls')),  
    path('accounts/', include('accountapp.urls')),
    path('memo/', include('memo.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG: 
#     import debug_toolbar 
#     urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]


gshs/models.py
from django.db import models
from datetime import datetime 
from django.core.exceptions import ValidationError
from django.db.models.fields import BLANK_CHOICE_DASH
from django.urls import reverse


class Infogigi(models.Model):
    productgubun = models.ForeignKey("gshs.Productgubun", on_delete=models.CASCADE, null=True, blank=True)
    buy_date = models.DateField(blank=True, null=True)
    people = models.ForeignKey("gshs.People", on_delete=models.CASCADE, null=True, blank=True, limit_choices_to = {'status': True})
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)    
    maker = models.CharField(max_length=50)
    model = models.CharField(max_length=100)  
    color_choices = (
        ('흑백', '흑백'),
        ('컬러', '컬러'),
    )  
    color = models.CharField(max_length=6, choices=color_choices, null=True, blank=True)    
    ip = models.CharField(max_length=20, blank=True, null=True)  
    status = models.BooleanField(default=True)  
    bigo = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ['productgubun','buy_date']
        db_table = 'infogigi'

    def __str__(self):
        return '{}'.format( self.model)

class Place(models.Model):
    building = models.CharField(max_length=50, null=True, blank=True)
    room = models.CharField(max_length=50, default=0, null=False, blank=True)
    buseo_choices = (
        ('부서', '부서'),
        ('강의실', '강의실'),
        ('강당', '강당'),
        ('실험실', '실험실'),
        ('기타', '기타'),
    )
    buseo = models.CharField(max_length=30, choices=buseo_choices)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['building']
        db_table = 'place'

    def __str__(self):
        return '({}) {}'.format(self.building, self.room)

class People(models.Model):
    name = models.CharField(u'성명', max_length=50, null=True, blank=True)  
    address = models.CharField('주소',max_length=100, null=True, blank=True)  
    phone_number = models.CharField(u'핸드폰', max_length=20, blank=True, null=True)
    tel_number = models.CharField(u'내선', max_length=5, blank=True, null=True)
    status = models.BooleanField('재직', default=True)
    bigo = models.CharField('비고', max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['name']
        db_table = 'people'

    def __str__(self):
        return '{}'.format(self.name)

class Jaego(models.Model):
    created_date = models.DateField(auto_now_add=True)    
    infogigi = models.ForeignKey("gshs.Infogigi", on_delete=models.SET_NULL, null=True)
    rental_choices = (
        ('yes', '대여가능'),
        ('no', '대여중'),
    )
    rental_status = models.CharField(max_length=3, choices=rental_choices, default='yes', null=False, blank=True)
    not_use = models.BooleanField(default=False)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-rental_status', '-created_date']
        db_table = 'jaego'

    def __str__(self):
        return '{}'.format(self.infogigi)

class Gigirental(models.Model):
    rental_date = models.DateField(auto_now_add=True)
    due_date = models.DateField(null=True, blank=True)
    jaego = models.ForeignKey("gshs.Jaego", on_delete=models.CASCADE, blank=True)
    people = models.ForeignKey("gshs.People", on_delete=models.CASCADE, null=True, blank=True, limit_choices_to = {'status': True})
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-rental_date']
        db_table = 'gigirental'

    def __str__(self):
        return '{}'.format(self.rental_date)

    def get_absolute_url(self):
        return reverse('gshs:gigirental_list')

class Repair(models.Model):
    created_date = models.DateField(auto_now_add=True)
    infogigi = models.ForeignKey("gshs.Infogigi", on_delete=models.SET_NULL, null=True, blank=True)
    place = models.ForeignKey("gshs.Place", on_delete=models.SET_NULL, null=True, blank=True)
    cause = models.CharField(max_length=200)
    result = models.TextField()      
    price = models.PositiveIntegerField(default=0, null=False, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-created_date']
        db_table = 'repair'

    def __str__(self):
        return '[{}] {}'.format(self.cause, self.result)

    def get_absolute_url(self):
        return reverse('gshs:suri_list')
    

class Productbuy(models.Model):
    created_date = models.DateField(auto_now_add=True)
    productgubun = models.ForeignKey("gshs.Productgubun", on_delete=models.CASCADE, null=True, blank=True)
    vendor = models.ForeignKey("gshs.Vendor", on_delete=models.CASCADE, null=True, blank=True)
    maker = models.CharField(max_length=50, null=True, blank=True)
    model = models.CharField(max_length=100)
    count = models.PositiveSmallIntegerField(default=1, blank=True)
    price = models.PositiveIntegerField(default=0, null=False, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['productgubun', 'model']
        db_table = 'productbuy'

    def __str__(self):
        return '{}'.format(self.model)

class Vendor(models.Model):
    created_date = models.DateField(auto_now_add=True)
    company = models.CharField(max_length=100)
    address = models.CharField(max_length=100, null=True, blank=True)
    damdang_name = models.CharField(max_length=20, null=True, blank=True)
    tel = models.CharField(max_length=20, null=True, blank=True)
    bigo = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ['company']
        db_table = 'vendor'

    def __str__(self):
        return f'{self.company}'


class Bupumchange(models.Model):
    created_date = models.DateField(auto_now_add=True)
    infogigi = models.ForeignKey("gshs.Infogigi", on_delete=models.SET_NULL, null=True, blank=True)
    productbuy = models.ForeignKey("gshs.Productbuy", on_delete=models.SET_NULL, null=True)
    count = models.PositiveSmallIntegerField(default=1, null=False, blank=True)
    price = models.PositiveIntegerField(default=0, null=False, blank=True)
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-created_date']
        db_table = 'bupumchange'

    # def __str__(self):
    #     return '{}'.format(self.productbuy)
class Productgubun(models.Model):
    main_division = models.CharField(max_length=30, default='infogigi')
    sub_division = models.CharField(max_length=50)

    class Meta:
        db_table = 'productgubun'

    def __str__(self):
        return '{} / {}'.format(self.main_division,self.sub_division)

def file_size(value): 
    limit = 3 * 1024 * 1024 
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MB.')

class Photo(models.Model):
    suri = models.ForeignKey("gshs.Repair", on_delete=models.CASCADE, null=True, blank=True)
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(validators=[file_size], upload_to = "images/%Y/%m", null=False, blank=True) 

    class Meta:
        db_table = 'photo'

    # def delete(self, *args, **kargs):
    #     if not self.image:
    #         self.__class__.objects.delete()
    #     super().delete(*args, **kargs)

class Softwarestock(models.Model):
    created_date = models.DateField(auto_now_add=True)
    maker = models.CharField(max_length=50, null=True, blank=True)
    model = models.CharField(max_length=100)
    license = models.TextField(null=True)
    count = models.PositiveSmallIntegerField(default=1, blank=True)
    price = models.PositiveIntegerField(default=0, null=False, blank=True) 
    remain = models.PositiveSmallIntegerField(null=True, blank=True) 

    class Meta:
        db_table = 'softwarestock'

    def __str__(self):
        return '{}'.format(self.model)

    # @property
    # def remaining2(self):
    #     if self.remaining is not None:
    #         return self.remaining
    #     return self.productbuy.count
    
class Softwarerental(models.Model):
    rental_date = models.DateField(auto_now_add=True)
    due_date = models.DateField(null=True, blank=True)
    softwarestock = models.ForeignKey("gshs.Softwarestock", on_delete=models.CASCADE, null=False, blank=True)    
    people = models.ForeignKey("gshs.People", on_delete=models.CASCADE, null=True, blank=True, limit_choices_to = {'status': True})
    place = models.ForeignKey("gshs.Place", on_delete=models.CASCADE, null=True, blank=True)
    count = models.PositiveSmallIntegerField(default=1, blank=True, help_text='남은 수량 보다 많이 입력하지마세요.!')
    bigo = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        ordering = ['-rental_date']
        db_table = 'softwarerental'

gshs/forms.py
from django import forms
from django.forms import inlineformset_factory
from gshs.models import Infogigi, Productbuy, Repair, Jaego, Photo, Gigirental, People, Softwarerental, Softwarestock, Bupumchange, Productgubun, Place
from gshs.widgets import AutoCompleteWidget, DatePickerWidget
from django.urls import reverse_lazy
from gshs.common.image_custom_widget import PreviewImageFileWidget

PhotoInlineFormSet = inlineformset_factory(Repair, Photo,\
    fields=['image',], extra=3)

class InfogigiForm(forms.ModelForm):  
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['productgubun'].queryset = Productgubun.objects.filter(main_division='infogigi')       


    class Meta:
        model = Infogigi
        fields = '__all__'  
        # widgets = {
        #     'productgubun': AutoCompleteWidget(ajax_url=reverse_lazy('gshs:productgubun_select')),
        #     'buy_date' : DatePickerWidget,
        # }         

class RepairForm(forms.ModelForm):
    class Meta:
        model = Repair
        fields = '__all__'

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['image'].required = False #file 값이 없더라도 view에서 유효성 검사에서 오류를 발생시키지 않도록 해준다
    #     self.fields['image'].widget.attrs.update({'class':'form-control-file'})
    #     self.fields['image'].multiple = True

class ProductbuyForm(forms.ModelForm):  
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['productgubun'].queryset = Productgubun.objects.all()    

    class Meta:
        model = Productbuy
        fields = '__all__'

class JaegoForm(forms.ModelForm):    
    class Meta:
        model = Jaego
        fields = '__all__'

class BupumchangeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['productbuy'].queryset = Productbuy.objects.filter(productgubun__main_division='consumables').select_related('productgubun')  

    class Meta:
        model = Bupumchange
        fields = ['productbuy','count','price','bigo']

class GigirentalForm(forms.ModelForm):    
    class Meta:
        model = Gigirental
        fields = ['jaego','people', 'place', 'bigo']
        widgets = {
            'jaego': forms.HiddenInput
        }

class PeopleForm(forms.ModelForm):    
    class Meta:
        model = People
        fields = '__all__'
    # def save(self, **kwargs):
    #     gigirental = super().save(commit=False)         # 부모메서드 호출 
    #     gigirental.infogigi.id = kwargs.get('infogigi_no', None)
    #     post.save()
class SoftwarestockForm(forms.ModelForm):
    class Meta:
        model = Softwarestock 
        fields = '__all__'
        widgets = {
            'remain': forms.HiddenInput
        }
        
class SoftwarerentalForm(forms.ModelForm):
    class Meta:
        model = Softwarerental
        fields = ['softwarestock','people', 'place', 'count', 'bigo']
        widgets = {
            'softwarestock': forms.HiddenInput
        }

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['place', 'image']
        # widgets = {
        #     'image': PreviewImageFileWidget()
        # }
PlaceImageFormSet = inlineformset_factory(Place, Photo,\
    fields=['image',], extra=2)

gshs/templates/gshs/place/edit_place_image.html
{% extends "base.html" %}

{% load static %}

{% block js %}
    <script type="text/javascript" src="{% static 'gshs/js/infogigis.js' %}"></script>
{% endblock %}

{% block content %}

<form method="post" action="{% url 'gshs:photo_place' place_id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Image Place</h4>        
    </div>
    <div class="modal-body">
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="id_place">Place</label>
        <input type="text" name="place" id="id_place" class="form-control" maxlength="100" value="{{ place_id }}">
        {% for error in field.errors %}
            <p class="help-block" sytle="color:red">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="id_images">Images</label>
          <input type="file" name="images" id="id_images" class="form-control-file" multiple  onchange="checkSize(this)">
          {% for error in field.errors %}
              <p class="help-block" sytle="color:red">{{ error }}</p>
          {% endfor %}
      </div>
    </div>
    <div class="modal-footer">        
        <button type="submit" class="btn btn-outline-info">submit</button>
    </div>
</form>

{% endblock %}

gshs/templates/gshs/place/list-place.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Place {% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'gshs/js/infogigis.js' %}"></script>
{% endblock %}

{% block content %}

<div style="display:flex;width:100%;justify-content: center;margin-top:40px;">
  <div class="place-left">
    <div class="place-left-sub"><h5>{{ gubun }}</h5></div>
      <ul>
        {% for item in object_list %}
        <li><a href="{% url 'gshs:list_place' item.room %}">{{item.building}}/{{item.room}}</a></li> 
        {% endfor %}    
      </ul>
  </div>

  <div class="place-right" style="position:relative;width:80%;padding:0 20px 20px;margin-left: 20px;margin-right:5%;">
    <div class="sub-title">
        <span class="bd-callout1">{{ place_gubun }}</span>
    </div>
    <a style="position:absolute; right:-20px; top:40;" class="custom-btn" href="{% url 'gshs:photo_place'  place_id %}" title="그림 삽입">
      <i class="far fa-images"></i>
    </a>
    <a style="position:absolute; right:-20px; top:80px;" class="custom-btn" href="{% url 'gshs:photo_update_place'  place_id %}" title="그림 수정">
      <i class="far fa-edit"></i>
    </a>
    <div style="margin-bottom:80px;">
      <div class="fotorama" data-fit="contain" data-allowfullscreen="true" data-nav="thumbs" data-width="100%">
        {% if place_number.photo_set.all %}            
            {% for photo in place_number.photo_set.all %}
                <a href="{{ photo.image.url }}"><img src="{{ photo.image.url }}"></a>
            {% endfor %}            
        {% endif %}
      </div>
    </div>
    {% if place_buseo_gubun == "부서" %}
      <div class="sub-title">
        <span class="bd-callout1" style="font-size:1rem;">부서원</span>
      </div>
      <div style="margin-bottom:80px;">
        <table class="place-table">
          <thead style="font-size: 14px;">
              <tr>
                <th>구분</th>
                <th>구매일</th>
                <th>성명</th>
                <th>제조사</th>
                <th>모델명</th>
                <th>Ip</th>
              </tr>
          </thead>
          <tbody>
              {% include './partial-place-peoplelist.html' %}
          </tbody>
        </table>
      </div>
    {% endif %}
    <div class="sub-title">
      <span class="bd-callout1" style="font-size:1rem;">기자재</span>
    </div>
    <div style="margin-bottom:80px;">
      <table class="place-table">
        <thead style="font-size: 14px;">
            <tr>
              <th>구분</th>
              <th>구매일</th> 
              <th>제조사</th>
              <th>모델명</th>                             
              <th>색상</th>              
              <th>Ip</th> 
            </tr>
        </thead>
        <tbody>
            {% include './partial-place-gigilist.html' %}
        </tbody>
      </table>   
    </div>
    <div  class="sub-title" style="position:relative;">
      <span class="bd-callout1" style="font-size:1rem;">수리</span>
      <button style="position:absolute; right:10px; top:0;" class="custom-btn js-suri-place {{ place_id }}" data-url="{% url 'gshs:suri_place'%}" title="공간내 수리">
        <i class="fas fa-tools"></i>
      </button>
    </div>
    <div style="margin-bottom:80px;">
      <table class="place-table">
        <thead style="font-size: 14px;">
            <tr>
              <th>수리일</th> 
              <th>제조사</th>
              <th>모델명</th>                             
              <th>원인</th>  
              <th>결과</th> 
              <th>금액</th> 
            </tr>
        </thead>
        <tbody>
            {% include './partial-place-surilist.html' %}
        </tbody>
      </table>   
    </div>
    <div class="sub-title">
      <span class="bd-callout1" style="font-size:1rem;">부품교체</span>
    </div>
    <div style="margin-bottom:50px;">
      <table class="place-table" id="infogigi-table">
        <thead style="font-size: 14px;">
            <tr>
               <th>교체일</th>
              <th>교체기기</th> 
              <th>부품명</th>
              <th>수량</th>
              <th>금액</th>  
            </tr>
        </thead>
        <tbody>
          {% include './partial-place-bupumlist.html' %}
        </tbody>
      </table>   
    </div>     
  </div>
</div>  

<div class="modal fade" id="modal-place">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

{% endblock content %}

gshs/templates/gshs/place/partial-place-bupumlist.html
{% load humanize %}
{% for items in place_bupum_list %}
  {% for item in items %} 
    <tr>
      <td>{{ item.created_date|date:'Y.m.d' }}</td>
      <td>{{ item.infogigi.place.room }}/{{item.infogigi }}</td>
      <td>{{ item.productbuy.model}}</td>           
      <td>{{ item.count }}</td>
      <td>&#8361;&nbsp;{{ item.price|intcomma }}</td>
    </tr>
  {% endfor %}
{% endfor %}

gshs/templates/gshs/place/partial-place-gigilist.html
{% for item in place_gigi_list %}
    <tr>
        <td>{{ item.productgubun.sub_division }}</td>
        <td>{{ item.buy_date|date:'Y.m.d'}}</td> 
        <td>{{ item.maker }}</td>
        <td>{{ item.model }}</td>       
        <td>{{ item.color }}</td>
        <td>{{ item.ip }}</td>    
    </tr>
{% endfor %}

gshs/templates/gshs/place/partial-place-peoplelist.html
{% for item in place_people_list %}
    <tr>  
        <td>{{ item.productgubun.sub_division }}</td>
        <td>{{ item.buy_date|date:'Y.m.d'}}</td>
        <td>{{ item.people }}</td>
        <td>{{ item.maker }}</td>
        <td>{{ item.model }}</td>  
        <td>{{ item.ip }}</td>    
    </tr> 
{% endfor %}

gshs/templates/gshs/place/partial-place-surilist.html
{% load humanize %}
{% for items in place_suri_list %}
  {% for item in items %}    
    <tr onClick="location.href='{% url "gshs:suri_list_pk" item.id %}'" style="cursor:pointer;">  
        <td>{{ item.created_date|date:'Y.m.d' }}</td>      
        <td>{{ item.infogigi.maker}}</td>
        <td>{{ item.infogigi.model}}</td>
        <td>{{ item.cause|truncatechars:7 }}</td>
        <td>{{ item.result|truncatechars:15 }}</td>    
        <td>&#8361;&nbsp;{{ item.price|intcomma }}</td>  
    </tr> 
  {% endfor %}
{% endfor %}

gshs/templates/gshs/place/photo-update-place.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% block title %}Update suri {% endblock %}

{% block extra-style %} {% endblock %}

{% block content %}
    <div style="margin-bottom:50px;color:#bfc144;">
        <h1>Upadte PlacePhoto</h1> 
        <hr>
    </div>    
    {% if form.errors %}
    <div>
        <div class="font-weight-bold">Wrong! please correct the form error(s) below.</div>
        {{form.errors}}
    </div>
    {% endif %}
    {% if formset.errors %}
    <div>
        <div class="font-weight-bold">Wrong! please correct the formset error(s) below.</div>
        {% for formerrors in formset.errors %}
            {{formerrors}}
        {% endfor %}
    </div>
    {% endif %}

    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="" method="post">
    {% endif %}
    {% csrf_token %}
        <h4>repair</h4>
        <fieldset class="card pt-5 pl-3 pr-3 pb-3">
            <div class="form-group row">
                {{ form.building|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.building|add_class:"form-control"}}
                </div>
            </div>
            <div class="form-group row">
                {{ form.room|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.room|add_class:"form-control"}}
                </div>
            </div>
            <div class="form-group row">
                {{ form.buseo|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.buseo|add_class:"form-control"}}
                </div>
            </div>            
        </fieldset>
        <br>

        <h4>photo</h4>
        <fieldset class="card pt-3">
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.id }}
            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold"}}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>
            <hr>
            {% endfor %}
        </fieldset>
        <div class="col-sm-12 mt-3" style="display: block; text-align: right; width: 100%;">
            <button class="custom-btn2">SUBMIT</button>
        </div>
    </form>
{% endblock content %}